import type React from "react"

/* ────────────────────────────────────────────────────────────────────
   KIKAR AI — Design Tokens
   Aligned with new dark charcoal + vivid green theme (globals.css)
──────────────────────────────────────────────────────────────────── */

export const T = {
  bg:          "#111111",
  bgAlt:       "#0d0d0d",
  surface:     "#1c1c1c",
  surfaceAlt:  "#232323",
  surfaceGlass:"rgba(255,255,255,0.04)",
  border:      "rgba(255,255,255,0.08)",
  borderHover: "rgba(255,255,255,0.14)",
  primary:     "hsl(119, 99%, 46%)",
  primaryDim:  "hsla(119, 99%, 46%, 0.15)",
  primaryFg:   "#0a0a0a",
  purple:      "#a855f7",
  purpleDim:   "rgba(168,85,247,0.15)",
  text:        "#f0f0f0",
  muted:       "#888888",
  muted2:      "#555555",
  red:         "#f87171",
  font:        "var(--font-sora), -apple-system, 'Segoe UI', sans-serif",
}

// Keep WA for backward compat (not used in new code, but avoids import errors)
export const WA = {
  bg:          T.bg,
  surface:     T.surface,
  surfaceAlt:  T.surfaceAlt,
  border:      T.border,
  green:       T.primary,
  greenDark:   T.primaryDim,
  textPrimary: T.text,
  textMuted:   T.muted,
  chatBg:      T.bgAlt,
}

export const CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    height: 100%;
    background: ${T.bg};
    color: ${T.text};
    font-family: ${T.font};
    -webkit-font-smoothing: antialiased;
  }
`

export const S: Record<string, React.CSSProperties> = {

  /* ── Auth ─────────────────────────────────────────────────────── */
  authWrap: {
    minHeight: "100dvh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: `radial-gradient(ellipse at 50% 0%, hsla(119,99%,46%,0.08) 0%, ${T.bg} 60%)`,
    padding: 16,
    fontFamily: T.font,
  },
  authCard: {
    background: "rgba(28,28,28,0.85)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    border: `1px solid ${T.border}`,
    borderRadius: 20,
    padding: "44px 32px",
    width: "100%",
    maxWidth: 400,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    boxShadow: "0 24px 64px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.04)",
    animation: "fade-up 0.5s cubic-bezier(0.16,1,0.3,1) both",
  },
  authLogo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  authLogoIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: T.primaryDim,
    border: `1px solid hsla(119,99%,46%,0.3)`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 26,
    boxShadow: `0 0 24px hsla(119,99%,46%,0.2)`,
  },
  authTitle: {
    margin: 0,
    textAlign: "center",
    fontSize: 22,
    color: T.text,
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  authSub: {
    margin: 0,
    textAlign: "center",
    color: T.muted,
    fontSize: 13,
    fontWeight: 400,
  },
  authTabRow: {
    display: "flex",
    borderRadius: 10,
    overflow: "hidden",
    border: `1px solid ${T.border}`,
    background: T.bgAlt,
  },
  authTab: {
    flex: 1,
    padding: "10px 0",
    background: "transparent",
    border: "none",
    color: T.muted,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    fontFamily: T.font,
    transition: "all 0.18s ease",
  },
  authTabActive: {
    background: T.surface,
    color: T.text,
    fontWeight: 600,
  },
  authInput: {
    width: "100%",
    padding: "12px 16px",
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    color: T.text,
    fontSize: 14,
    fontFamily: T.font,
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.18s ease, box-shadow 0.18s ease",
  },
  authBtn: {
    padding: "14px 0",
    background: `linear-gradient(135deg, ${T.primary} 0%, hsl(119,99%,38%) 100%)`,
    border: "none",
    borderRadius: 10,
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    color: T.primaryFg,
    marginTop: 4,
    fontFamily: T.font,
    letterSpacing: "0.01em",
    transition: "opacity 0.18s ease, transform 0.12s ease",
    boxShadow: `0 4px 24px hsla(119,99%,46%,0.25)`,
  },

  /* ── Sidebar ──────────────────────────────────────────────────── */
  sideTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 16px",
    background: T.surface,
    borderBottom: `1px solid ${T.border}`,
    flexShrink: 0,
  },
  brand: {
    fontWeight: 700,
    fontSize: 15,
    color: T.text,
    letterSpacing: "-0.02em",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  brandDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: T.primary,
    boxShadow: `0 0 8px ${T.primary}`,
  },
  signOutBtn: {
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    color: T.muted,
    fontSize: 13,
    borderRadius: 8,
    padding: "5px 10px",
    cursor: "pointer",
    fontFamily: T.font,
    transition: "border-color 0.18s, color 0.18s",
  },
  tabBar: {
    display: "flex",
    padding: "10px 12px",
    gap: 6,
    background: T.surface,
    borderBottom: `1px solid ${T.border}`,
    flexShrink: 0,
  },
  tabBtn: {
    flex: 1,
    padding: "9px 0",
    background: "transparent",
    border: `1px solid ${T.border}`,
    borderRadius: 8,
    color: T.muted,
    fontSize: 12,
    fontWeight: 500,
    fontFamily: T.font,
    cursor: "pointer",
    letterSpacing: "0.01em",
    transition: "all 0.18s ease",
  },
  tabBtnActive: {
    background: T.primaryDim,
    borderColor: `hsla(119,99%,46%,0.35)`,
    color: T.primary,
    fontWeight: 600,
  },
  listWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  newCharBtn: {
    margin: "12px 12px 6px",
    padding: "11px 0",
    background: "transparent",
    border: `1px dashed hsla(119,99%,46%,0.4)`,
    borderRadius: 10,
    color: T.primary,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: T.font,
    cursor: "pointer",
    flexShrink: 0,
    transition: "background 0.18s, border-color 0.18s",
    letterSpacing: "0.01em",
  },
  charList: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  charItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    cursor: "pointer",
    borderBottom: `1px solid ${T.border}`,
    transition: "background 0.15s",
  },
  charItemActive: {
    background: T.primaryDim,
    borderLeft: `2px solid ${T.primary}`,
  },
  charEmoji: {
    fontSize: 24,
    flexShrink: 0,
    width: 40,
    height: 40,
    borderRadius: 10,
    background: T.bgAlt,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  charName: {
    fontSize: 14,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: T.text,
    fontWeight: 500,
  },
  charMeta: {
    fontSize: 11,
    color: T.muted,
    marginTop: 2,
  },
  delBtn: {
    background: "transparent",
    border: "none",
    color: T.muted2,
    cursor: "pointer",
    fontSize: 14,
    padding: "4px 6px",
    borderRadius: 6,
    flexShrink: 0,
    transition: "color 0.15s, background 0.15s",
  },
  userEmail: {
    fontSize: 11,
    color: T.muted2,
    padding: "10px 16px",
    flexShrink: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    borderTop: `1px solid ${T.border}`,
  },
  searchRow: {
    display: "flex",
    gap: 6,
    padding: "10px 12px",
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    padding: "10px 14px",
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    color: T.text,
    fontSize: 13,
    fontFamily: T.font,
    outline: "none",
  },
  searchBtn: {
    width: 40,
    height: 40,
    background: T.primary,
    border: "none",
    borderRadius: 10,
    color: T.primaryFg,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 16,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  /* ── Chat / DM shared ────────────────────────────────────────── */
  backBtn: {
    alignItems: "center",
    justifyContent: "center",
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    color: T.text,
    fontSize: 16,
    cursor: "pointer",
    padding: "0",
    width: 34,
    height: 34,
    borderRadius: 8,
    flexShrink: 0,
    lineHeight: 1,
    fontFamily: T.font,
    transition: "border-color 0.15s",
  },
  chatWrap: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    overflow: "hidden",
    height: "100%",
  },
  chatHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 16px",
    background: T.surface,
    borderBottom: `1px solid ${T.border}`,
    flexShrink: 0,
    backdropFilter: "blur(12px)",
  },
  chatName: {
    fontSize: 15,
    fontWeight: 600,
    color: T.text,
    letterSpacing: "-0.01em",
  },
  chatSub: {
    fontSize: 11,
    color: T.muted,
    marginTop: 1,
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  bubble: {
    padding: "10px 14px",
    borderRadius: 14,
    lineHeight: 1.55,
    fontSize: 14,
    wordBreak: "break-word",
    fontWeight: 400,
    animation: "fade-in 0.2s ease both",
  },
  bubbleUser: {
    background: `linear-gradient(135deg, ${T.primary} 0%, hsl(119,99%,38%) 100%)`,
    color: T.primaryFg,
    alignSelf: "flex-end",
    borderBottomRightRadius: 4,
    boxShadow: `0 2px 12px hsla(119,99%,46%,0.2)`,
    fontWeight: 500,
  },
  bubbleAI: {
    background: T.surface,
    border: `1px solid ${T.border}`,
    color: T.text,
    alignSelf: "flex-start",
    borderBottomLeftRadius: 4,
  },
  inputRow: {
    display: "flex",
    gap: 8,
    padding: "10px 14px",
    background: T.surface,
    borderTop: `1px solid ${T.border}`,
    flexShrink: 0,
    paddingBottom: "max(10px,env(safe-area-inset-bottom))",
    alignItems: "center",
  },
  chatInput: {
    flex: 1,
    padding: "11px 16px",
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    borderRadius: 999,
    color: T.text,
    outline: "none",
    fontSize: 14,
    fontFamily: T.font,
    transition: "border-color 0.18s, box-shadow 0.18s",
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: `linear-gradient(135deg, ${T.primary}, hsl(119,99%,38%))`,
    border: "none",
    fontSize: 17,
    cursor: "pointer",
    color: T.primaryFg,
    fontWeight: 700,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "opacity 0.15s, transform 0.12s",
    boxShadow: `0 2px 12px hsla(119,99%,46%,0.3)`,
  },
  imgBtn: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: T.bgAlt,
    border: `1px solid ${T.border}`,
    fontSize: 17,
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "border-color 0.15s",
  },

  /* ── Empty / Placeholder states ──────────────────────────────── */
  empty: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    padding: 32,
    background: T.bgAlt,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    background: T.primaryDim,
    border: `1px solid hsla(119,99%,46%,0.25)`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 32,
    boxShadow: `0 0 32px hsla(119,99%,46%,0.12)`,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: T.text,
    textAlign: "center",
    letterSpacing: "-0.01em",
  },
  emptyText: {
    color: T.muted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 1.7,
    maxWidth: 240,
  },
  emptyBtn: {
    padding: "12px 28px",
    background: `linear-gradient(135deg, ${T.primary} 0%, hsl(119,99%,38%) 100%)`,
    border: "none",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    color: T.primaryFg,
    fontFamily: T.font,
    letterSpacing: "0.01em",
    boxShadow: `0 4px 20px hsla(119,99%,46%,0.25)`,
    transition: "opacity 0.15s, transform 0.12s",
  },

  /* ── Forms ────────────────────────────────────────────────────── */
  formWrap: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 20px",
    background: T.bgAlt,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: T.text,
    marginBottom: 20,
    letterSpacing: "-0.02em",
  },
  label: {
    fontSize: 11,
    color: T.muted,
    display: "block",
    marginBottom: 6,
    marginTop: 16,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    fontWeight: 600,
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    color: T.text,
    fontSize: 14,
    fontFamily: T.font,
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.18s, box-shadow 0.18s",
  },
  textarea: {
    width: "100%",
    padding: "12px 16px",
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    color: T.text,
    fontSize: 14,
    fontFamily: T.font,
    outline: "none",
    resize: "vertical",
    boxSizing: "border-box",
    transition: "border-color 0.18s, box-shadow 0.18s",
  },
  emojiGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  emojiBtn: {
    fontSize: 22,
    padding: "8px 10px",
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  emojiBtnActive: {
    borderColor: `hsla(119,99%,46%,0.6)`,
    background: T.primaryDim,
    boxShadow: `0 0 12px hsla(119,99%,46%,0.2)`,
    transform: "scale(1.08)",
  },
  formBtns: {
    display: "flex",
    gap: 10,
    marginTop: 28,
  },
  cancelBtn: {
    flex: 1,
    padding: "13px 0",
    background: "transparent",
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    color: T.muted,
    fontSize: 13,
    fontFamily: T.font,
    fontWeight: 500,
    cursor: "pointer",
    transition: "border-color 0.18s, color 0.18s",
  },
  createBtn: {
    flex: 2,
    padding: "13px 0",
    background: `linear-gradient(135deg, ${T.primary} 0%, hsl(119,99%,38%) 100%)`,
    border: "none",
    borderRadius: 10,
    fontWeight: 700,
    fontSize: 14,
    fontFamily: T.font,
    cursor: "pointer",
    color: T.primaryFg,
    letterSpacing: "0.01em",
    boxShadow: `0 4px 20px hsla(119,99%,46%,0.25)`,
    transition: "opacity 0.15s, transform 0.12s",
  },
  dimText: {
    color: T.muted,
    fontSize: 13,
    padding: "16px",
  },
}